import offstage from "@/assets/images/OffStage/offstage";
const OffStageDetails = [
  {
    eventName: "Rangoli",
    facultyCoordinator:
      "Ms. Shamadhani Begum (Department of Science and Humanities)",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "Girls hostel – E block road",
    time: "11:00 a.m.",
    description: [
      "Rangoli art should be of 5ft X 5ft",
      "Maximum time for Duo is 30 minutes while maximum time for Solo will be 1 hour.",
      "All required materials should be brought by the participants themselves.",
      "Usage of salt other than suji colours and flowers should be avoided",
      "Use of phones, tablets or printouts as a preference will lead to immediate disqualification.",
      "Evaluation will be based on theme, colour combinations, creativity and clarity of rangoli",
    ],
    image: offstage.Rangoli,
    reverse: false,
  },
  {
    eventName: "Face Painting",
    facultyCoordinator:
      "Ms. Sathya (Department of Artificial Intelligence and Data Science)",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "E-Block",
    time: "11:00 a.m.",
    description: [
      "The team must have 2 members- the one who paints and the other whose face is to be painted",
      "All the required materials must be brought by the participants.",
      "Time limit for face painting is 1 hour.",
      "Theme will be given on the spot",
      "Use of phones, tablets or printouts as a preference will lead to immediate disqualification.",
      "Participants will be judged on the basis of creativity, innovation and design.",
    ],
    image: offstage.FacePainting,
    reverse: true,
  },
  {
    eventName: "Mehandi",
    facultyCoordinator:
      "Ms. Sharmila (Department of Computer Science and Engineering)",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "A-Block",
    time: "12:00 p.m.",
    description: [
      "Participants must bring their own materials.",
      "Participants have to apply mehandi on the palmer as well as the dorsal side of the hand",
      "Participants can apply mehandi on their own hand or any other person’s hand",
      "The Time limit will be 1 hour.",
      "Judging will be based on neatness and creativity.",
    ],
    image: offstage.Mehandi,
    reverse: false,
  },
  {
    eventName: "Reels",
    facultyCoordinator:
      "Mr. Sivaji Rao (Photo Club - Department Of Computer Science And Design)",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "A-Block",
    time: "11:00 a.m.",
    description: [
      "Minimum time limit: 15 seconds",
      "Maximum time limit: 30 seconds",
      "Participants should act and present their own video to the audience.",
      "The videos will be displayed on screen at the event, and the winners will be chosen",
    ],
    image: offstage.Reels,
    reverse: true,
  },
  {
    eventName: "Short Film",
    facultyCoordinator:
      "Mr. Arunkumar (Riders Club - Department Of Mechanical Engineering)",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "A-Block",
    time: "11:00 a.m.",
    description: [
      "Individual event.",
      "The film should have a time limit of 5 minutes",
      "Animations are allowed",
      "Films in other languages are permitted but should have subtitles in English",
      "The short film must be original. No copyright issues should be claimed.",
    ],
    image: offstage.ShortFilm,
    reverse: false,
  },
  {
    eventName: "Photography",
    facultyCoordinator:
      "Dr.V. Sharmila (Photography Club - Department of Science and Humanities)",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "A-Block",
    time: "10:00 a.m. - 2:00p.m",
    description: [
      "Mobile and DSLR photography are allowed (DSLR- recommended)",
      "Theme will be given on-spot.",
      "The participant has to capture 3 photographs on the theme announced on the spot by the judges",
      "Each participant is allowed to submit one picture taken at the given spot",
      "All photographs must be original. No watermark or editing is allowed",
      "Device used to take picture must be mentioned along with your details",
      "Digital images are evaluated on the basis of (I) IMPACT, (II) COMPOSITION. (III) TECHNICAL QUALITY, and (IV) SUITABILITY for the specific theme",
      "The additional instructions will be announced on the spot.",
    ],
    image: offstage.Photography,
    reverse: true,
  },
  {
    eventName: "Fireless Cooking",
    facultyCoordinator: "Dr. A. Kavitha (Department of Science and Humanities)",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "A-Block",
    time: "1:00 p.m.",
    description: [
      "2 members in a team",
      "Total preparation must be 35-40 minutes",
      "Participants must exhibit a chart with the name of food and ingredients used to prepare it",
      "Participants could prepare numerous dishes in the stipulated time",
      "Participants must bring the required cooking items (NOTE: only working table will be provided)",
      "Only vegetarian dishes are allowed to cook",
      "The Cutting of vegetables/fruits should be done on the spot",
      "Participants are allowed to bring non-electric equipment (mixer, chopper, juicer, grater etc.,)",
      "Evaluation will be based on table cleanliness, presentation and taste of the food",
    ],
    image: offstage.FirelessCooking,
    reverse: false,
  },
  {
    eventName: "Vegetable Carving",
    facultyCoordinator:
      "Ms . Charumathi  ( Department of Science and Humanities)",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "A – Block",
    time: "12 : 00 pm",
    description: [
      "All contestants are required to produce one sculpture that are made entirely of fruits/ vegetables.",
      "No flowers other than those sculpted of fruits/vegetables are allowed.",
      "The contestant will have one hour to complete the piece for judging.",
      "All pieces are to be made of entirely edible food. No plastic supports in frames.",
      "Added colors are acceptable.",
      "Extra emphasis will be placed on the use of the natural shapes and colours of the fruit/vegetables and how they are used to support and enhance each other.",
      "All tools including hand tools like chisels, knives, saws, drills, angle cutters, shaped Cutters, power drimmels, other power tools like squares, levels are acceptable",
      "No pre preparation of vegetables or fruits before competition is allowed",
      "Participants should not take the help of others to complete the task.",
    ],
    image: offstage.VegetableCarving,
    reverse: true,
  },
  {
    eventName: "Nail Art",
    facultyCoordinator:
      "Ms. Vidhya Lakshmi ( Department Of Electrical and Electronics Engineering )",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "A – Block",
    time: "12 PM",
    description: [
      "No mobile phones, tablets or smart watches during the competition for both the competitor and the model.",
      "No outside communication with competitors while competitions are going on.",
      "Competitors allowed to prepare the natural nail prior to the competition. But absolutely no application work of any kind until the competition officially begins.",
      "Complete one hand with gel polish on natural nails. No extensions. Three pink and white French manicure style nails and two nails a flat crème red.",
      "Competitors using a model will have 30 minutes to complete one hand.",
      "Competitors working on themselves will receive 5 extra minutes.",
    ],
    image: offstage.NailArt,
    reverse: false,
  },
  {
    eventName: "Craft Art",
    facultyCoordinator:
      "Ms. Gopika ( Art and Craft Club -School of Business Administration )",
    facultyNumber: "+91 97867 63812",
    studentCoordinator: "V.Deepakkumar V",
    studentNumber: "+91 97867 63812",
    venue: "A – Block",
    time: "12 PM",
    description: [
      "No mobile phones, tablets or smart watches during the competition for both the competitor and the model.",
      "No outside communication with competitors while competitions are going on.",
      "Competitors are not allowed to prepare the craft prior to the competition. And absolutely no application work of any kind until the competition officially begins.",
      "Competitors are allowed to use water colors, paper, cardboard and necessary materials have to be brought by themselves.",
      "Competitors will have 30 minutes to complete the craft.",
      "Final results will be decided by the allocated judges.",
    ],
    image: offstage.CarftArt,
    reverse: true,
  },
];

export default OffStageDetails;
