import onstage from "@/assets/images/OnStage/onstage";

const OnStageDetails = [
  {
    eventName: "Solo Singing",
    facultyCoordinator:
      "Ms. Ramsheena, AP/SH (Kindle Club)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "LBS Hall",
    time: "9:30 AM",
    description: [
      "Only Individual participants are allowed.",
      "Performance timing must be within 2-3 mins.",
      "Participant must bring instrument or instrumental music with self to perform. (Pen drive).",
      "Judgment will be based on tal, selection of raga, composition and general impression.",
      "The decision of the jury shall be final.",
      "Top six contestants will be selected to the final round.",
    ],
    image: onstage.SoloSinging,
    reverse: false,
  },
  {
    eventName: "Solo Dance",
    facultyCoordinator:
      "Mr. Arun Kumar AP/ME (Riders Club)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "MG Hall",
    time: "9:30 a.m.",
    description: [
      "Time limit for the performance will be 3 to 5 minutes.",
      "Any style of dance is accepted, but No Vulgar songs, dress and steps.",
      "If the Number of participants increases prelims time for every participant will be reduced.",
      "Props required for the performance must be brought by the participants. Usage of fire and glass as props is not encouraged.",
      "The participants are asked to bring the songs/track in pen-drive.",
      "The decision of the jury shall be final with regard to the interpretation of the rules.",
      "Top six contestants will be selected to final round.",
    ],
    image: onstage.SoloDancing,
    reverse: true,
  },
  {
    eventName: "Group Dance",
    facultyCoordinator:
      "Ms. Saranya, AP/ECE (Music and Dance Club)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "Auditorium",
    time: "10:00 a.m.",
    description: [
      "Any style of dance is accepted, but No Vulgar songs, dress and steps.",
      "The Group must contain either girls or boys i.e., no mixed groups",
      "Maximum 10 participants allowed per team. The team may consist of all boys, all girls or a mixture of both.",
      "Duration of dance should not be more than 5 minutes.",
      "If the Number of participants increase prelims time for every team will be reduced",
      "Props required for the performance must be brought by the participants. Usage of fire and glass as props is not encouraged",
      "The participants are asked to bring their sounds/track in pen-drive.",
      "The participating team will be responsible for removal of their sets / properties etc. immediately after the completion of their performance.",
      "Judgment will be based on the qualities like Tal, Technique, Rhythm, Abhinaya or Expression, Costumes, Footwork and general impression etc.",
    ],
    image: onstage.GroupDance,
    reverse: false,
  },
  {
    eventName: "Instrumentals",
    facultyCoordinator:
      "Mr. Prabhu, AP/S&H (My Campus Clubs)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "Auditorium",
    time: "12:00 p.m.",
    description: [
      "The team must contain a maximum of 8 members",
      "The Performance will last approximately 4-5 minutes",
      "Participants should bring their own musical instruments for the performance",
      "Maximum of 3 singers in a group and Number of accompanists playing instruments shall be six.",
      "Instruments of western origin adopted to the India Raga system are allowed",
      "Maximum time allowed for the instrumental music is 10 minutes which include setting time. The setting time for a group shall not exceed 4 minutes.",
      "Judgment will be made on the qualities like, composition rhythm, coordination and general impression.",
    ],
    image: onstage.Instrumentals,
    reverse: true,
  },
  {
    eventName: "Adapt Tune",
    facultyCoordinator:
      "Mr. Pradeep Kumar, AP/ CE(Riders Club)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "MG Hall",
    time: "1:00 p.m.",
    description: [
      "Individual on-stage event.",
      "Time duration: 1-2 minutes",
      "Participants must adapt their dance styles to the music played.",
      "Judgment will be made base don expression, Choreography, Energy, and Attire.",
      "The decision of the jury shall be final with regard to the interpretation of the rules.",
    ],
    image: onstage.AdaptTune,
    reverse: false,
  },
  {
    eventName: "Stand up",
    facultyCoordinator:
      "Ms. Charumathi, AP/S&H (Kindle Club)",
    facultyNumber: "+91 99943 76667",
    studentCoordinator: "",
    studentNumber: "",
    venue: "Conference hall (E-block)",
    time: "1:00 p.m.",
    description: [
      "Variety events like mimicry, solo instrumentals, stand-up comedy, beatbox and others",
      "Each participant will be given 3-5 minutes to prove themselves",
      "Best talents will be awarded.",
      "MIMICRY:",
      "Each student artist shall be given 5 minutes time.",
      "Participants may mimic the sound of machines, speeches of a well-known persons etc.,",
      "Marks will be awarded based on skill imitating, variety of sound and voice imitation and presentation",
      "STAND-UP COMEDY:",
      "Only solo participants are allowed",
      "No participant may make any reference to individuals or religion and any dual meaning obscene content is strictly prohibited",
    ],
    image: onstage.standup,
    reverse: true,
  },
  {
    eventName: "Skit & Mime",
    facultyCoordinator:
      "Dr. C. Arulmurugan, AP/ETE(Radio Club)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "Conference hall (E-block)",
    time: "10:00 a.m.",
    description: [
      "MIME:",
      "Time duration: Maximum of 5 minutes",
      "Props and music is allowed.",
      "Their music should only contain instrumental and no lyrics.",
      "The act should not contain any dialogue or lip sync.",
      "Judgement will be based on innovation, depiction of the situation, team work and expressions.",
      "The decision of the jury shall be final with regard to the interpretation of the rules.",
      "SKIT:",
      "The teams will be free to select the theme/story/script of the skit",
      "Maximum of 8 and minimum of 4 participants will be allowed.",
      "The teams will be given 2-3 minutes time for arrangement of props.",
      "The team will be allowed to perform for 3-5 minutes",
      "Necessary props must be arranged by the participants",
      "Act will be judged based on the script, facial expression, stage presence, co-ordination, voice modulation and overall performance.",
    ],
    image: onstage.mime,
    reverse: false,
  },
  {
    eventName: "Ethnic Walk",
    facultyCoordinator:
      "Ms . Adlin Princy(Kindle Club)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "Auditorium",
    time: "2:00 p.m.",
    description: [
      "Each participant/ team will be given a minute on stage.",
      "Individual / Couple of participants will be permitted.",
      "Participants are asked not to wear any revealing cloths.",
      "Participants should bring their own cloths, makeup and accessories for the walk.",
      "Garments and accessories used for competition should depict the ethnicity of the country, state or any other culture.",
      "Any form of indecency, vulgarity, obscenity will result in disqualification.",
    ],
    image: onstage.Walk,
    reverse: true,
  },
  {
    eventName: "RJ/VJ Hunt",
    facultyCoordinator:
      "Dr. Saminathan, ASP/ EC(Tamil Mandram)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "KIC",
    time: "12:00 p.m",
    description: [
      "Only individual participants are allowed",
      "Participants have to prepare a script on the given topic at the time of the event",
      "Both Tamil and English languages can be used.",
      "Time limit will be 6 minutes (3min for preparation and 3min for presentation)",
      "Participants will be judged on the basis of scripts, presentation, voice modulation, voice quality",
    ],
    image: onstage.rj,
    reverse: false,
  },
  {
    eventName: "Variety Event",
    facultyCoordinator:
      "Ms Monisha L, AP / SH(Tamil Mandram)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "Conference hall (E-block)",
    time: "1:00 p.m.",
    description: [
      "Variety events like mimicry, solo instrumentals, stand-up comedy, beatbox and others",
      "Each participant will be given 3-5 minutes to prove themselves",
      "Best talents will be awarded.",
      "MIMICRY:",
      "Each student artist shall be given 5 minutes time.",
      "Participants may mimic the sound of machines, speeches of a well-known persons etc.,",
      "Marks will be awarded based on skill imitating, variety of sound and voice imitation and presentation",
      "STAND-UP COMEDY:",
      "Only solo participants are allowed",
      "No participant may make any reference to individuals or religion and any dual meaning obscene content is strictly prohibited",
    ],
    image: onstage.Variety,
    reverse: true,
  },
  
];

export default OnStageDetails;
